# This section specifies the input data
data:
  # Specify the dataset file
  resource: ../../../single_task/ChEMBL_permissive_CYP3A4_CHEMBL340_aggregated.parquet
  type: intake
  input_col: OPENADMET_SMILES
  # Specify each (1+) of the target columns, or the column that you're trying to predict
  target_cols: pchembl_value_mean
  dropna: true

# Additional metadata
metadata:
  authors: Sean M Colby
  biotargets:
  - CYP3A4
  build_number: 0
  # Description of the experiment
  description: basic regression trained on AChE and fine-tuned to CYP3A4 pChEMBL using ChemProp
  driver: pytorch
  email: sea.colby@omsf.io
  name: CYP3A4_pchembl_finetune_testing_chemprop
  tag: openadmet-CYP3A4-pchembl-finetune-regression-testing
  tags:
  - CYP3A4
  - openadmet
  - test
  - pchembl
  - finetuning
  version: v1

# Section specifying training procedure
procedure:
  # Featurization specification
  feat:
    # Using the ChemPropFeaturizer (for ChemProp model)
    # See openadmet.models.features
    type: ChemPropFeaturizer
    params:
      batch_size: 128
      normalize_targets: true
      n_jobs: 4

  # Model specification
  model:
    # Indicate model type
    # See openadmet.models.architecture
    type: ChemPropModel
    # Specify paths to pretrained model weights and parameters for fine-tuning
    serial_path: ache_chemprop_anvil_model_dir/model.pth
    param_path: ache_chemprop_anvil_model_dir/model.json
    # Specify which weights to freeze during fine-tuning
    freeze_weights:
      message_passing: true
      batch_norm: false
      ffn_layers: 0
    params: {}

  # Specify data splits
  split:
    # Specify how data will be split
    # See openadmet.models.split
    type: ShuffleSplitter
    # Specify split parameters
    params:
      random_state: 42
      test_size: 0.2
      train_size: 0.7
      val_size: 0.1

  # Specify training configuration
  train:
    # Specify the trainer, here LightningTrainer as ChemProp is a PyTorch Lightning model
    # See openadmet.models.trainer
    type: LightningTrainer
    # Specify model parameters
    params:
      accelerator: gpu
      early_stopping: true
      early_stopping_patience: 10
      early_stopping_mode: min
      early_stopping_min_delta: 0.001
      max_epochs: 50
      monitor_metric: val_loss
      use_wandb: false
      wandb_project: demos # Specify wandb project name according to guidelines

# Section specifying report generation
report:
  # Configure evaluation
  eval:
  # Generate regression metrics
  - type: RegressionMetrics
    params: {}

  # Generate regression plots
  - type: RegressionPlots
    params:
      axes_labels:
      - True pChEMBL
      - Predicted pChEMBL
      max_val: 10
      min_val: 3
      pXC50: true
      title: Multitask True vs Predicted pChEMBL on test set