feat:
  params:
    featurizers:
      DescriptorFeaturizer:
        descr_type: desc2d
      FingerprintFeaturizer:
        fp_type: ecfp:4
  type: FeatureConcatenator
model:
  params:
    alpha: 0.005
    learning_rate: 0.05
  type: LGBMRegressorModel
split:
  params:
    random_state: 42
    test_size: 0.3
    train_size: 0.7
    val_size: 0.0
  type: ShuffleSplitter
train:
  params:
    param_grid:
      alpha:
      - 0.005
      learning_rate:
      - 0.05
      n_estimators:
      - 500
  type: SKLearnGridSearchTrainer
