data:
  anvil_dir: file:///home/xuc2/skunkworks/gpu_testing/gpu_runs/lgbm
  cat_entry: null
  dropna: true
  input_col: OPENADMET_SMILES
  resource: ../multitask.csv
  target_cols:
  - cyp3a4_pchembl_value_mean
  type: intake
metadata:
  authors: Cynthia Xu
  biotargets:
  - CYP3A4
  build_number: 0
  description: basic regression using a LightGBM model
  driver: sklearn
  email: cynthia.xu@omsf.io
  name: lgbm_pchembl
  tag: openadmet-PXR-chembl
  tags:
  - openadmet
  - test
  - pchembl
  version: v1
procedure:
  feat:
    params:
      featurizers:
        DescriptorFeaturizer:
          descr_type: desc2d
        FingerprintFeaturizer:
          fp_type: ecfp:4
    type: FeatureConcatenator
  model:
    params:
      alpha: 0.005
      learning_rate: 0.05
    type: LGBMRegressorModel
  split:
    params:
      random_state: 42
      test_size: 0.3
      train_size: 0.7
      val_size: 0.0
    type: ShuffleSplitter
  train:
    params:
      param_grid:
        alpha:
        - 0.005
        learning_rate:
        - 0.05
        n_estimators:
        - 500
    type: SKLearnGridSearchTrainer
report:
  eval:
  - params: {}
    type: RegressionMetrics
  - params:
      axes_labels:
      - True pAC50
      - Predicted pAC50
      max_val: 10
      min_val: 3
      n_repeats: 2
      n_splits: 5
      pXC50: true
      title: Multitask True vs Predicted pAC50 on test set
    type: SKLearnRepeatedKFoldCrossValidation
